include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error
    avoid_print: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Errors & safety
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    no_duplicate_case_values: true

    # Style — effective_dart
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true
    unnecessary_string_interpolations: true
    unnecessary_brace_in_string_interps: true
    prefer_is_empty: true
    prefer_is_not_empty: true

    # Types
    always_declare_return_types: true
    annotate_overrides: true
    avoid_init_to_null: true
    prefer_typing_uninitialized_variables: true
    type_init_formals: true

    # Organization
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    prefer_const_constructors_in_immutables: true

    # Readability
    curly_braces_in_flow_control_structures: true
    prefer_adjacent_string_concatenation: true
    prefer_spread_collections: true
    prefer_collection_literals: true
    avoid_unnecessary_containers: true
